import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import "./globals.css";
import localFont from "next/font/local";
import Layout from "@/components/layout/Layout";

const pinarFont= localFont({
  src: '../../public/fonts/pinar.ttf'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={pinarFont.className}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
